In [1]:
import flwr as fl
print(f"Flower version: {fl.__version__}")


Flower version: 1.13.0


In [3]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.utils import shuffle

# Dataset names
dataset_names = [
    "test.csv", "train.csv", "all.csv", "dev.csv", "test_hidden.csv",
    "train_fewshot-128.csv", "train_fewshot-32.csv",
    "train_fewshot-512.csv", "train_fewshot-8.csv"
]

# Load datasets into a dictionary
datasets = {}
for dataset_name in dataset_names:
    try:
        df = pd.read_csv(dataset_name)
        datasets[dataset_name] = df
    except Exception as e:
        print(f"Error loading {dataset_name}: {e}")

# Preprocess data - ensuring the 'ad_creative_body' column is present
for name, df in datasets.items():
    if 'ad_creative_body' not in df.columns:
        print(f"Warning: 'ad_creative_body' column not found in {name}")
    else:
        print(f"Loaded {name} with {len(df)} rows.")

# Preprocess text data (cleaning and normalization)
def preprocess_text(text):
    # Remove special characters, convert to lowercase, and return
    text = text.lower()
    text = ''.join(e for e in text if e.isalnum() or e.isspace())
    return text

# Prepare the vectorizer and labels
all_text = []
for df in datasets.values():
    if not df.empty and 'ad_creative_body' in df.columns:
        all_text.extend(df["ad_creative_body"].apply(preprocess_text).values)

# Create a global TF-IDF vectorizer
global_vectorizer = TfidfVectorizer(stop_words='english')
global_vectorizer.fit(all_text)

# Federated Client class
class FederatedClient:
    def __init__(self, name, X_train, X_test, y_train, y_test):
        self.name = name
        self.X_train = X_train
        self.X_test = X_test
        self.y_train = y_train
        self.y_test = y_test
        self.model = self.build_model()

    def build_model(self):
        # Build a Neural Network Model
        model = Sequential()
        model.add(Dense(512, input_dim=self.X_train.shape[1], activation='relu'))
        model.add(Dropout(0.2))
        model.add(Dense(256, activation='relu'))
        model.add(Dropout(0.2))
        model.add(Dense(128, activation='relu'))
        model.add(Dropout(0.2))
        model.add(Dense(max_classes, activation='softmax'))  # For multi-class classification
        
        model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
        return model

    def train(self):
        self.model.fit(self.X_train, self.y_train, epochs=5, batch_size=32, verbose=2)

    def evaluate(self):
        y_pred = np.argmax(self.model.predict(self.X_test), axis=1)
        return accuracy_score(self.y_test, y_pred), classification_report(self.y_test, y_pred), confusion_matrix(self.y_test, y_pred)

    def get_parameters(self):
        return self.model.get_weights()

    def set_parameters(self, parameters):
        self.model.set_weights(parameters)

# Prepare Federated Learning clients
clients = []
max_classes = 0  # Track the maximum number of classes across clients
for name, df in datasets.items():
    if 'ad_creative_body' in df.columns and 'Typology 1' in df.columns:
        X = df["ad_creative_body"].apply(preprocess_text).values
        y = df["Typology 1"].values.astype(str)  # Convert target labels to string

        valid_rows = ~pd.isna(y)
        X = X[valid_rows]
        y = y[valid_rows]

        if len(np.unique(y)) < 2:
            print(f"Skipping {name} as it contains fewer than 2 classes.")
            continue

        max_classes = max(max_classes, len(np.unique(y)))

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        X_train_tfidf = global_vectorizer.transform(X_train).toarray()
        X_test_tfidf = global_vectorizer.transform(X_test).toarray()

        # Encode the labels as integers
        label_map = {label: idx for idx, label in enumerate(np.unique(y))}
        y_train_encoded = np.array([label_map[label] for label in y_train])
        y_test_encoded = np.array([label_map[label] for label in y_test])

        client = FederatedClient(name, X_train_tfidf, X_test_tfidf, y_train_encoded, y_test_encoded)
        clients.append(client)

# Federated Training function
def federated_training(clients, num_rounds=10):
    global_weights = clients[0].model.get_weights()

    for round_num in range(num_rounds):
        local_weights = []

        # Train each client and collect their weights
        for client in clients:
            client.set_parameters(global_weights)
            client.train()
            local_weights.append(client.get_parameters())

        # Aggregate weights (FedAvg)
        avg_weights = [np.mean(np.array([local_weights[i][j] for i in range(len(local_weights))]), axis=0) for j in range(len(local_weights[0]))]
        global_weights = avg_weights

        # Update clients with the new global weights
        for client in clients:
            client.set_parameters(global_weights)

        # Evaluate the clients
        accuracies = []
        for client in clients:
            try:
                accuracy, report, conf_matrix = client.evaluate()
                print(f"Client {client.name} - Accuracy: {accuracy:.4f}")
                accuracies.append(accuracy)
                print("Classification Report:")
                print(report)
                print("Confusion Matrix:")
                print(conf_matrix)
            except IndexError as e:
                print(f"Evaluation error for client {client.name}: {e}")
                accuracies.append(0)  # Assign zero accuracy if evaluation fails

        avg_accuracy = np.mean(accuracies)
        print(f"Round {round_num + 1}/{num_rounds}, Average accuracy: {avg_accuracy:.4f}")

 
#  For Running  federated training and  prediction                              
federated_training(clients, num_rounds=10)


Loaded test.csv with 255 rows.
Loaded train.csv with 913 rows.
Loaded all.csv with 1330 rows.
Loaded dev.csv with 162 rows.
Loaded test_hidden.csv with 255 rows.
Loaded train_fewshot-128.csv with 128 rows.
Loaded train_fewshot-32.csv with 32 rows.
Loaded train_fewshot-512.csv with 512 rows.
Loaded train_fewshot-8.csv with 8 rows.


C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Skipping test_hidden.csv as it contains fewer than 2 classes.
Epoch 1/5
7/7 - 6s - 822ms/step - accuracy: 0.2598 - loss: 2.0493
Epoch 2/5
7/7 - 0s - 48ms/step - accuracy: 0.3235 - loss: 1.8890
Epoch 3/5
7/7 - 0s - 53ms/step - accuracy: 0.3333 - loss: 1.6324
Epoch 4/5
7/7 - 0s - 47ms/step - accuracy: 0.4657 - loss: 1.3868
Epoch 5/5
7/7 - 0s - 46ms/step - accuracy: 0.6667 - loss: 1.0758
Epoch 1/5
23/23 - 6s - 266ms/step - accuracy: 0.2575 - loss: 1.9384
Epoch 2/5
23/23 - 1s - 35ms/step - accuracy: 0.5438 - loss: 1.4379
Epoch 3/5
23/23 - 1s - 36ms/step - accuracy: 0.7521 - loss: 0.7443
Epoch 4/5
23/23 - 1s - 36ms/step - accuracy: 0.8712 - loss: 0.3764
Epoch 5/5
23/23 - 1s - 35ms/step - accuracy: 0.9644 - loss: 0.1785
Epoch 1/5
34/34 - 6s - 185ms/step - accuracy: 0.3148 - loss: 1.8645
Epoch 2/5
34/34 - 1s - 34ms/step - accuracy: 0.6212 - loss: 1.1705
Epoch 3/5
34/34 - 1s - 40ms/step - accuracy: 0.8289 - loss: 0.4989
Epoch 4/5
34/34 - 1s - 34ms/step - accuracy: 0.9492 - loss: 0.2216
Epoch 5

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


1/6 ━━━━━━━━━━━━━━━━━━━━ 1s 229ms/stepWARNING:tensorflow:6 out of the last 31 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x00000204D872B7E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Client train.csv - Accuracy: 0.6885
Classification Report:
              precision    recall  f1-score   support

           0       0.48      1.00      0.65        32
           1       0.00      

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Client all.csv - Accuracy: 0.6353
Classification Report:
              precision    recall  f1-score   support

           0       0.47      1.00      0.64        50
           1       0.00      0.00      0.00        26
           2       1.00      0.28      0.43        18
           3       1.00      0.17      0.29        18
           4       0.69      0.91      0.79        55
           5       0.00      0.00      0.00         9
           6       0.00      0.00      0.00        14
           7       0.77      0.80      0.79        76

    accuracy                           0.64       266
   macro avg       0.49      0.39      0.37       266
weighted avg       0.59      0.64      0.56       266

Confusion Matrix:
[[50  0  0  0  0  0  0  0]
 [22  0  0  0  3  0  0  1]
 [ 6  0  5  0  1  0  0  6]
 [ 0  0  0  3  9  0  0  6]
 [ 3  0  0  0 50  0  0  2]
 [ 3  0  0  0  3  0  0  3]
 [12  0  0  0  2  0  0  0]
 [11  0  0  0  4  0  0 61]]


C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step
Client dev.csv - Accuracy: 0.2727
Classification Report:
              precision    recall  f1-score   support

           0       0.39      1.00      0.56         7
           1       0.00      0.00      0.00         4
           3       0.00      0.00      0.00        14
           4       0.17      0.40      0.24         5
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         0

    accuracy                           0.27        33
   macro avg       0.08      0.20      0.11        33
weighted avg       0.11      0.27      0.15        33

Confusion Matrix:
[[ 7  0  0  0  0  0  0]
 [ 4  0  0  0  0  0  0]
 [ 3  0  0 10  0  0  1]
 [ 3  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0]]


C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step
Client train_fewshot-128.csv - Accuracy: 0.6923
Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         6
           1       0.00      0.00      0.00         2
           2       1.00      0.50      0.67         4
           4       1.00      1.00      1.00         6
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         2
           7       0.67      1.00      0.80         4

    accuracy                           0.69        26
   macro avg       0.45      0.50      0.45        26
weighted avg       0.60      0.69      0.61        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [0 0 2 0 0 0 2]
 [0 0 0 6 0 0 0]
 [2 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [0 0 0 0 0 0 4]]


C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step
Client train_fewshot-32.csv - Accuracy: 0.7143
Classification Report:
              precision    recall  f1-score   support

           0       0.33      1.00      0.50         1
           4       1.00      1.00      1.00         2
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       1.00      1.00      1.00         2

    accuracy                           0.71         7
   macro avg       0.47      0.60      0.50         7
weighted avg       0.62      0.71      0.64         7

Confusion Matrix:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 2]]


C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
Client train_fewshot-512.csv - Accuracy: 0.7670
Classification Report:
              precision    recall  f1-score   support

           0       0.62      1.00      0.77        25
           1       0.00      0.00      0.00         6
           2       1.00      0.71      0.83         7
           3       0.00      0.00      0.00         5
           4       0.79      0.96      0.86        23
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         6
           7       0.90      0.90      0.90        30

    accuracy                           0.77       103
   macro avg       0.41      0.45      0.42       103
weighted avg       0.66      0.77      0.70       103

Confusion Matrix:
[[25  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  0  0]
 [ 0  0  5  0  1  0  0  1]
 [ 0  0  0  0  3  0  0  2]
 [ 1  0  0  0 22  0  0  0]
 [ 1  0  0  0  0  0  0  0]
 [ 5  0  0  0  1  0  0  0]
 [ 2  0  0  0  1  0  0 27]]


C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step
Client train_fewshot-8.csv - Accuracy: 0.0000
Classification Report:
              precision    recall  f1-score   support

           2       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       1.0
           7       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

Confusion Matrix:
[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
Round 1/10, Average accuracy: 0.5473


C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

Epoch 1/5
7/7 - 0s - 44ms/step - accuracy: 0.7108 - loss: 1.1724
Epoch 2/5
7/7 - 0s - 45ms/step - accuracy: 0.8039 - loss: 0.6351
Epoch 3/5
7/7 - 0s - 45ms/step - accuracy: 0.8824 - loss: 0.3496
Epoch 4/5
7/7 - 0s - 46ms/step - accuracy: 0.9657 - loss: 0.1977
Epoch 5/5
7/7 - 0s - 45ms/step - accuracy: 0.9804 - loss: 0.1033
Epoch 1/5
23/23 - 1s - 38ms/step - accuracy: 0.7658 - loss: 0.8632
Epoch 2/5
23/23 - 1s - 37ms/step - accuracy: 0.9644 - loss: 0.1706
Epoch 3/5
23/23 - 1s - 36ms/step - accuracy: 0.9945 - loss: 0.0361
Epoch 4/5
23/23 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0123
Epoch 5/5
23/23 - 1s - 35ms/step - accuracy: 0.9986 - loss: 0.0089
Epoch 1/5
34/34 - 1s - 33ms/step - accuracy: 0.7622 - loss: 0.8401
Epoch 2/5
34/34 - 1s - 33ms/step - accuracy: 0.9643 - loss: 0.1566
Epoch 3/5
34/34 - 1s - 33ms/step - accuracy: 0.9897 - loss: 0.0428
Epoch 4/5
34/34 - 1s - 33ms/step - accuracy: 0.9981 - loss: 0.0177
Epoch 5/5
34/34 - 1s - 34ms/step - accuracy: 0.9991 - loss: 0.0065
Epoch

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
Client train.csv - Accuracy: 0.9016
Classification Report:
              precision    recall  f1-score   support

           0       0.78      1.00      0.88        32
           1       1.00      0.69      0.81        16
           2       1.00      0.78      0.88        18
           3       0.78      1.00      0.88         7
           4       0.88      1.00      0.94        38
           5       1.00      0.83      0.91         6
           6       1.00      0.77      0.87        13
           7       0.96      0.91      0.93        53

    accuracy                           0.90       183
   macro avg       0.93      0.87      0.89       183
weighted avg       0.92      0.90      0.90       183

Confusion Matrix:
[[32  0  0  0  0  0  0  0]
 [ 4 11  0  0  1  0  0  0]
 [ 1  0 14  2  0  0  0  1]
 [ 0  0  0  7  0  0  0  0]
 [ 0  0  0  0 38  0  0  0]
 [ 0  0  0  0  0  5  0  1]
 [ 2  0  0  0  1  0 10  0]
 [ 2  0  0  0  3  0  0 48]]
9/9 ━━━━━━━━━━━━━

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
Client train_fewshot-128.csv - Accuracy: 0.8846
Classification Report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      0.50      0.67         2
           2       1.00      0.75      0.86         4
           4       0.86      1.00      0.92         6
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       0.80      1.00      0.89         4

    accuracy                           0.88        26
   macro avg       0.93      0.82      0.85        26
weighted avg       0.90      0.88      0.87        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 1 0 1 0 0 0]
 [0 0 3 0 0 0 1]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   su

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

7/7 - 0s - 45ms/step - accuracy: 0.9314 - loss: 0.3461
Epoch 2/5
7/7 - 0s - 45ms/step - accuracy: 0.9804 - loss: 0.1167
Epoch 3/5
7/7 - 0s - 45ms/step - accuracy: 1.0000 - loss: 0.0520
Epoch 4/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0279
Epoch 5/5
7/7 - 0s - 45ms/step - accuracy: 1.0000 - loss: 0.0121
Epoch 1/5
23/23 - 1s - 35ms/step - accuracy: 0.9685 - loss: 0.2287
Epoch 2/5
23/23 - 1s - 34ms/step - accuracy: 0.9959 - loss: 0.0377
Epoch 3/5
23/23 - 1s - 34ms/step - accuracy: 0.9973 - loss: 0.0153
Epoch 4/5
23/23 - 1s - 33ms/step - accuracy: 0.9986 - loss: 0.0076
Epoch 5/5
23/23 - 1s - 57ms/step - accuracy: 1.0000 - loss: 0.0032
Epoch 1/5
34/34 - 1s - 33ms/step - accuracy: 0.9511 - loss: 0.2636
Epoch 2/5
34/34 - 1s - 33ms/step - accuracy: 0.9915 - loss: 0.0424
Epoch 3/5
34/34 - 1s - 38ms/step - accuracy: 0.9981 - loss: 0.0126
Epoch 4/5
34/34 - 1s - 33ms/step - accuracy: 0.9991 - loss: 0.0064
Epoch 5/5
34/34 - 1s - 32ms/step - accuracy: 0.9991 - loss: 0.0049
Epoch 1/5
5/5 -

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
Client train_fewshot-128.csv - Accuracy: 0.9615
Classification Report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         4

    accuracy                           0.96        26
   macro avg       0.98      0.93      0.94        26
weighted avg       0.97      0.96      0.96        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   su

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

Epoch 1/5
7/7 - 0s - 53ms/step - accuracy: 0.9510 - loss: 0.1513
Epoch 2/5
7/7 - 0s - 44ms/step - accuracy: 0.9755 - loss: 0.0716
Epoch 3/5
7/7 - 0s - 51ms/step - accuracy: 1.0000 - loss: 0.0333
Epoch 4/5
7/7 - 0s - 43ms/step - accuracy: 0.9951 - loss: 0.0179
Epoch 5/5
7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0076
Epoch 1/5
23/23 - 1s - 34ms/step - accuracy: 0.9959 - loss: 0.0690
Epoch 2/5
23/23 - 1s - 34ms/step - accuracy: 0.9959 - loss: 0.0292
Epoch 3/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0087
Epoch 4/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0042
Epoch 5/5
23/23 - 1s - 33ms/step - accuracy: 1.0000 - loss: 0.0026
Epoch 1/5
34/34 - 1s - 32ms/step - accuracy: 0.9803 - loss: 0.1035
Epoch 2/5
34/34 - 1s - 33ms/step - accuracy: 0.9962 - loss: 0.0255
Epoch 3/5
34/34 - 1s - 33ms/step - accuracy: 0.9972 - loss: 0.0164
Epoch 4/5
34/34 - 1s - 34ms/step - accuracy: 0.9991 - loss: 0.0089
Epoch 5/5
34/34 - 1s - 33ms/step - accuracy: 0.9981 - loss: 0.0101
Epoch

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Client train_fewshot-128.csv - Accuracy: 0.9615
Classification Report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         4

    accuracy                           0.96        26
   macro avg       0.98      0.93      0.94        26
weighted avg       0.97      0.96      0.96        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   su

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

7/7 - 0s - 43ms/step - accuracy: 0.9951 - loss: 0.0580
Epoch 2/5
7/7 - 0s - 43ms/step - accuracy: 0.9951 - loss: 0.0334
Epoch 3/5
7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0145
Epoch 4/5
7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0076
Epoch 5/5
7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0054
Epoch 1/5
23/23 - 1s - 33ms/step - accuracy: 0.9986 - loss: 0.0243
Epoch 2/5
23/23 - 1s - 34ms/step - accuracy: 0.9986 - loss: 0.0108
Epoch 3/5
23/23 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0054
Epoch 4/5
23/23 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0037
Epoch 5/5
23/23 - 1s - 33ms/step - accuracy: 0.9986 - loss: 0.0036
Epoch 1/5
34/34 - 1s - 33ms/step - accuracy: 0.9887 - loss: 0.0522
Epoch 2/5
34/34 - 1s - 38ms/step - accuracy: 0.9915 - loss: 0.0338
Epoch 3/5
34/34 - 1s - 35ms/step - accuracy: 0.9991 - loss: 0.0087
Epoch 4/5
34/34 - 1s - 33ms/step - accuracy: 0.9991 - loss: 0.0037
Epoch 5/5
34/34 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0019
Epoch 1/5
5/5 -

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Client train_fewshot-128.csv - Accuracy: 0.9615
Classification Report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         4

    accuracy                           0.96        26
   macro avg       0.98      0.93      0.94        26
weighted avg       0.97      0.96      0.96        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   su

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

7/7 - 0s - 44ms/step - accuracy: 0.9951 - loss: 0.0324
Epoch 2/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0137
Epoch 3/5
7/7 - 0s - 51ms/step - accuracy: 1.0000 - loss: 0.0064
Epoch 4/5
7/7 - 0s - 45ms/step - accuracy: 1.0000 - loss: 0.0041
Epoch 5/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0034
Epoch 1/5
23/23 - 1s - 37ms/step - accuracy: 0.9973 - loss: 0.0155
Epoch 2/5
23/23 - 1s - 36ms/step - accuracy: 0.9973 - loss: 0.0184
Epoch 3/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0040
Epoch 4/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0023
Epoch 5/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0018
Epoch 1/5
34/34 - 1s - 33ms/step - accuracy: 0.9906 - loss: 0.0300
Epoch 2/5
34/34 - 1s - 34ms/step - accuracy: 0.9934 - loss: 0.0258
Epoch 3/5
34/34 - 1s - 34ms/step - accuracy: 0.9944 - loss: 0.0170
Epoch 4/5
34/34 - 1s - 33ms/step - accuracy: 0.9991 - loss: 0.0064
Epoch 5/5
34/34 - 1s - 40ms/step - accuracy: 1.0000 - loss: 0.0021
Epoch 1/5
5/5 -

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
Client train_fewshot-128.csv - Accuracy: 0.9615
Classification Report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         4

    accuracy                           0.96        26
   macro avg       0.98      0.93      0.94        26
weighted avg       0.97      0.96      0.96        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   su

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

Epoch 1/5
7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0147
Epoch 2/5
7/7 - 0s - 45ms/step - accuracy: 1.0000 - loss: 0.0065
Epoch 3/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0071
Epoch 4/5
7/7 - 0s - 52ms/step - accuracy: 1.0000 - loss: 0.0043
Epoch 5/5
7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 1/5
23/23 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0058
Epoch 2/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0028
Epoch 3/5
23/23 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0023
Epoch 4/5
23/23 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0015
Epoch 5/5
23/23 - 1s - 34ms/step - accuracy: 1.0000 - loss: 9.4180e-04
Epoch 1/5
34/34 - 1s - 34ms/step - accuracy: 0.9944 - loss: 0.0212
Epoch 2/5
34/34 - 1s - 35ms/step - accuracy: 0.9972 - loss: 0.0134
Epoch 3/5
34/34 - 1s - 34ms/step - accuracy: 0.9991 - loss: 0.0043
Epoch 4/5
34/34 - 1s - 39ms/step - accuracy: 1.0000 - loss: 0.0022
Epoch 5/5
34/34 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0012
E

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
Client train_fewshot-128.csv - Accuracy: 0.9615
Classification Report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         4

    accuracy                           0.96        26
   macro avg       0.98      0.93      0.94        26
weighted avg       0.97      0.96      0.96        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   s

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

7/7 - 0s - 43ms/step - accuracy: 0.9951 - loss: 0.0157
Epoch 2/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0066
Epoch 3/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0035
Epoch 4/5
7/7 - 0s - 49ms/step - accuracy: 1.0000 - loss: 0.0061
Epoch 5/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0027
Epoch 1/5
23/23 - 1s - 34ms/step - accuracy: 0.9973 - loss: 0.0088
Epoch 2/5
23/23 - 1s - 36ms/step - accuracy: 0.9973 - loss: 0.0218
Epoch 3/5
23/23 - 1s - 35ms/step - accuracy: 0.9986 - loss: 0.0076
Epoch 4/5
23/23 - 1s - 32ms/step - accuracy: 1.0000 - loss: 0.0030
Epoch 5/5
23/23 - 1s - 37ms/step - accuracy: 1.0000 - loss: 0.0013
Epoch 1/5
34/34 - 1s - 33ms/step - accuracy: 0.9934 - loss: 0.0202
Epoch 2/5
34/34 - 1s - 34ms/step - accuracy: 0.9981 - loss: 0.0083
Epoch 3/5
34/34 - 1s - 39ms/step - accuracy: 0.9972 - loss: 0.0131
Epoch 4/5
34/34 - 1s - 34ms/step - accuracy: 0.9981 - loss: 0.0088
Epoch 5/5
34/34 - 1s - 33ms/step - accuracy: 0.9991 - loss: 0.0026
Epoch 1/5
5/5 -

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
Client train_fewshot-128.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         4

    accuracy                           1.00        26
   macro avg       1.00      1.00      1.00        26
weighted avg       1.00      1.00      1.00        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   su

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0092
Epoch 2/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0050
Epoch 3/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0027
Epoch 4/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0017
Epoch 5/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0014
Epoch 1/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0028
Epoch 2/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 0.0014
Epoch 3/5
23/23 - 1s - 36ms/step - accuracy: 1.0000 - loss: 8.7993e-04
Epoch 4/5
23/23 - 1s - 38ms/step - accuracy: 1.0000 - loss: 9.0467e-04
Epoch 5/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 5.0873e-04
Epoch 1/5
34/34 - 1s - 33ms/step - accuracy: 0.9991 - loss: 0.0083
Epoch 2/5
34/34 - 1s - 34ms/step - accuracy: 0.9991 - loss: 0.0082
Epoch 3/5
34/34 - 1s - 33ms/step - accuracy: 1.0000 - loss: 0.0024
Epoch 4/5
34/34 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0013
Epoch 5/5
34/34 - 1s - 34ms/step - accuracy: 1.0000 - loss: 8.2556e-04

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
Client train_fewshot-128.csv - Accuracy: 0.9615
Classification Report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         4

    accuracy                           0.96        26
   macro avg       0.98      0.93      0.94        26
weighted avg       0.97      0.96      0.96        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   su

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0055
Epoch 2/5
7/7 - 0s - 44ms/step - accuracy: 0.9951 - loss: 0.0076
Epoch 3/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0029
Epoch 4/5
7/7 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 5/5
7/7 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 1/5
23/23 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0023
Epoch 2/5
23/23 - 1s - 36ms/step - accuracy: 1.0000 - loss: 9.9361e-04
Epoch 3/5
23/23 - 1s - 59ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 4/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 7.1116e-04
Epoch 5/5
23/23 - 1s - 35ms/step - accuracy: 1.0000 - loss: 5.2031e-04
Epoch 1/5
34/34 - 1s - 33ms/step - accuracy: 0.9972 - loss: 0.0098
Epoch 2/5
34/34 - 1s - 33ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 3/5
34/34 - 1s - 33ms/step - accuracy: 1.0000 - loss: 9.1026e-04
Epoch 4/5
34/34 - 1s - 34ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 5/5
34/34 - 1s - 40ms/step - accuracy: 1.0000 - loss: 0.0012

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
Client train_fewshot-128.csv - Accuracy: 0.9615
Classification Report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         4

    accuracy                           0.96        26
   macro avg       0.98      0.93      0.94        26
weighted avg       0.97      0.96      0.96        26

Confusion Matrix:
[[6 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 2 0 0]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
Client train_fewshot-32.csv - Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   su

C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\OneDrive\Desktop\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\krish\